### ISSUE TITLE
Missing imports in convert-table when creating a schema

### ISSUE THREAD

**Issue by lidalei** [limehome/bq-schema#16]
When using convert-table to create an existing BigQuery table's schema, the generated Python file misses imports, such as
```
from typing import Optional
from bq_schema.types.type_mapping import Timestamp
```
.

**Comment by raphaelbrand** [comment]
Hi,

thanks for checking our our library! Unfortunately it is not mentioned in the README, but the convert-table script is more meant as a starting point, then a final solution. We use it so infrequently that we just add the imports manually afterwards.
We are open to code contributions though, so if you feel like sending a PR, you might want to look here:

https://github.com/limehome/bq-schema/blob/master/bq_schema/cli/convert_table.py

I will close this for now, but feel free to open another issue in case you decide to work on it.
