### ISSUE TITLE
feature request: add support to BigQuery table clustering spec via `clustering_fields`

### ISSUE THREAD

**Issue by lidalei** [limehome/bq-schema#17]
We often partition as well as cluster a big table in BigQuery. Currently `BigqueryTable` supports `time_partitioning`. I would like to request the support of clustering fields.

Ref: https://cloud.google.com/bigquery/docs/creating-clustered-tables#creating_an_empty_clustered_table_with_a_schema_definition

**Comment by raphaelbrand** [comment]
Sorry for the late answer but are you still looking for this? Should be not that hard to add, but if you are not using the library right now I would skip the feature :)

**Comment by lidalei** [comment]
> Sorry for the late answer but are you still looking for this? Should be not that hard to add, but if you are not using the library right now I would skip the feature :)

No worries! Nah. You may skip the feature. Thx!
