### ISSUE TITLE
Loosen google-cloud-bigquery dependancy

### ISSUE THREAD

**Issue by matsavage** [limehome/bq-schema#19]
I would like to use this package in a project I am working on, however I cannot import it into my code base as the `google-cloud-bigquery=="1.24.0"` requirement is very strict, especially as `2.x.x` and now `3.x.x` versions of the bigquery API are now live.

Is this something which is on your roadmap?

**Comment by raphaelbrand** [comment]
Hey thanks for pointing that out. This library was never tested with the newer versions. Let me try it out and see how it goes. If the tests still pass I don't see a reason why we should not bump the version.

**Comment by raphaelbrand** [comment]
https://github.com/limehome/bq-schema/pull/20 
Updating to 2.0.0 seems very easy, I am not sure about 3.0.0. I think this would take a bit more testing. Let me know what you think.

**Comment by matsavage** [comment]
Looks great, thanks!
